# Site settings
name: "Evan Cummings"
title: "- Evan Cummings -"
email: emcummings@gmail.com
description: "Sweet description goes here"
baseurl: ""
url: "http://evancummings.com"
twitter_id: "480071863058452480"
tagline: "I'm that guy with the pony tail"
# Build settings
markdown: kramdown
permalinks: pretty

